# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Formatter-FOAFKnows-vCard
version:      0.1
version_from: lib/Formatter/FOAFKnows/vCard.pm
installdirs:  site
requires:
    Digest::SHA1:                  0
    Text::vCard:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
